name: Validate Terraform with Trivy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  RunTerraformValidation:
    name: Run Terraform SAST
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #Check formatting
      - name: Terraform fmt check
        run: |
          terraform fmt -check -recursive || {
            echo "Terraform formatting check failed. Run 'terraform fmt -recursive' locally to fix it.!"
            exit 1
          }

      - name: Terraform validate
        run: |
          terraform init -backend=false
          terraform validate

      #Validate each module folder
      - name: Validate all modules
        run: |
          set -e
          for dir in $(find . -type f -name "main.tf" -exec dirname {} \;); do
            echo "Validating module in $dir"
            (cd "$dir" && terraform init -backend=false -input=false && terraform validate -no-color)
          done

      # Results have to be a table as the organisation does not have Advanced Security license.
      - name: Terraform Trivy Scan
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: 'config'
          exit-code: '1'
